---
title: "427_target"
output: html_document
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
df_target<- read.csv('427data_target.csv')
head(df_target)



```

```{r}
variables_to_test <- df_target[, c("JA", "SA", "ABA")]
par(mfrow = c(1, 3))

for (variable_name in colnames(variables_to_test)) {
  qqnorm(variables_to_test[[variable_name]], main = paste("QQ Plot for", variable_name))
  qqline(variables_to_test[[variable_name]], col = "red")
}
```

```{r}
#检查正态分布
shapiro_test_result <- lapply(variables_to_test, shapiro.test)

for (column_name in names(shapiro_test_result)) {
  cat("Shapiro-Wilk normality test for variable", column_name, ":\n")
  print(shapiro_test_result[[column_name]])
  cat("\n")
}

```

```{r}
#log transform
df_target$log_JA <- log(df_target$JA + 1) 

par(mfrow = c(1, 2))

qqnorm(df_target$JA, main = "QQ Plot for JA")
qqline(df_target$JA, col = "red")

qqnorm(df_target$log_JA, main = "QQ Plot for log-transformed JA")
qqline(df_target$log_JA, col = "red")


```

```{r}
df_target$log_ABA <- log(df_target$ABA + 1) 

par(mfrow = c(1, 2))

qqnorm(df_target$ABA, main = "QQ Plot for ABA")
qqline(df_target$ABA, col = "red")

qqnorm(df_target$log_ABA, main = "QQ Plot for log-transformed ABA")
qqline(df_target$log_ABA, col = "red")
```

```{r}
logvariables_to_test <- df_target[, c("log_JA","log_ABA")]
shapiro_test_result <- lapply(logvariables_to_test, shapiro.test)

for (column_name in names(shapiro_test_result)) {
  cat("Shapiro-Wilk normality test for variable", column_name, ":\n")
  print(shapiro_test_result[[column_name]])
  cat("\n")
}

```

```{r}
#separate df into days
df_d1 <- subset(df_target, time_point == 1)

df_d2 <- subset(df_target, time_point == 2)

df_d3 <- subset(df_target, time_point == 3)
df_d3
```

```{r}
#Anova for SA in days
df_list <- list(df_d1, df_d2, df_d3)

for (i in 1:length(df_list)) {
  df <- df_list[[i]]
  cat("Summary for df_day", i, ":\n")
  model_SA <- aov(SA ~ exp_group, data = df)
  print(summary(model_SA))
}

```

```{r}
#Tukey's HSD for SA in day3
model_SA3 <- aov(SA~exp_group,data = df_d3)
tukey_result_d3 <- TukeyHSD(model_SA3)

print(tukey_result_d3)



```

```{r}
#Anova for log_ABA in days
df_list <- list(df_d1, df_d2, df_d3)

for (i in 1:length(df_list)) {
  df <- df_list[[i]]
  cat("Summary for df_day", i, ":\n")
  model_ABA <- aov(log_ABA ~ exp_group, data = df)
  print(summary(model_ABA))
}

```

```{r}
#Tukey's HSD for log_ABA in day3
model_logABA_d3 <- aov(log_ABA~exp_group,data = df_d3)
tukey_result_logABA_d3 <- TukeyHSD(model_logABA_d3)

print(tukey_result_logABA_d3)



```

```{r}
# add a column named treatment
df_target$treatment <- ifelse(grepl("Control", df_target$exp_group), "control",
                       ifelse(grepl("H1st", df_target$exp_group), "H1st",
                              ifelse(grepl("F1st", df_target$exp_group), "F1st", NA)))

print(df_target)


```
```{r}
library(car)

df_target$treatment <- as.factor(df_target$treatment)
leveneTest(SA ~ treatment, data = df_target)


```
```{r}
leveneTest(SA ~ treatment, data = df_target)


```
```{r}
treatment_df <- data.frame()

treatment_df <- rbind(treatment_df, subset(df_target, !grepl("control", treatment)))

print(treatment_df)


```


```{r}
#Anova  order significant different?
dependent_variables <- c("SA", "log_ABA")
model_summaries <- list()
normality_results <- list()
homogeneity_results <- list()

# Loop for ANOVA and assumption tests
for (var in dependent_variables) {
    formula <- as.formula(paste(var, "~ treatment"))
    model <- aov(formula, data = treatment_df)
    model_summaries[[var]] <- summary(model)
    
    # Normality test of residuals
    residuals_data <- residuals(model)
    normality_results[[var]] <- shapiro.test(residuals_data)
    
    # Homogeneity of variances test
    homogeneity_results[[var]] <- leveneTest(formula, data = df_target)
}

# Loop for displaying results
for (var in dependent_variables) {
    cat("Summary for", var, ":\n")
    print(model_summaries[[var]])
    cat("\n")
    
    cat("Normality test result for residuals of", var, ":\n")
    print(normality_results[[var]])
    cat("\n")
    
    cat("Homogeneity of variances test result for", var, ":\n")
    print(homogeneity_results[[var]])
    cat("\n")
}


```



```{r}
treatment_df_d3 <- subset(treatment_df, time_point == 3)

treatment_df_d3



```
```{r}
#check whether the order cause the significant different focus on day3 data. 
dependent_variables <- c("SA", "log_ABA")

model_summaries <- list()

for (var in dependent_variables) {
  formula <- as.formula(paste(var, "~ treatment"))
  model <- aov(formula, data = treatment_df_d3)
  model_summaries[[var]] <- summary(model)
}


for (var in dependent_variables) {
  cat("Summary for", var, ":\n")
  print(model_summaries[[var]])
  cat("\n")
}

```


```{r}
#get control group
control_df <- data.frame()

control_df <- rbind(control_df, subset(df_target, grepl("control", treatment)))


print(control_df)

```

```{r}
control_treatment1_df <- data.frame()

control_treatment1_df <- rbind(control_treatment1_df, subset(df_target, !grepl("F1st", treatment)))

print(control_treatment1_df)


```

```{r}
control_treatment2_df <- data.frame()

control_treatment2_df <- rbind(control_treatment2_df, subset(df_target, !grepl("H1st", treatment)))

print(control_treatment2_df)


```






```{r}
#Anova control and treatment H1st significant different?
dependent_variables <- c("SA", "log_ABA")

model_summaries <- list()

for (var in dependent_variables) {
  formula <- as.formula(paste(var, "~ treatment"))
  model <- aov(formula, data = control_treatment1_df)
  model_summaries[[var]] <- summary(model)
}


for (var in dependent_variables) {
  cat("Summary for", var, ":\n")
  print(model_summaries[[var]])
  cat("\n")
}


```

```{r}
#Anova control and treatment F1st significant different?
dependent_variables <- c("SA", "log_ABA")

model_summaries <- list()

for (var in dependent_variables) {
  formula <- as.formula(paste(var, "~ treatment"))
  model <- aov(formula, data = control_treatment2_df)
  model_summaries[[var]] <- summary(model)
}


for (var in dependent_variables) {
  cat("Summary for", var, ":\n")
  print(model_summaries[[var]])
  cat("\n")
}


```



```{r}
#consider if the order significant different？
dependent_variables <- c("SA", "log_ABA")

model_summaries <- list()

for (var in dependent_variables) {
  formula <- as.formula(paste(var, "~ treatment"))
  model <- aov(formula, data = treatment_df)
  model_summaries[[var]] <- summary(model)
}


for (var in dependent_variables) {
  cat("Summary for", var, ":\n")
  print(model_summaries[[var]])
  cat("\n")
}


```


