---
title: "427 targeted"
author: "Mingqian Fu"
date: "2024-02-26"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
data<-read_excel('DADY_targeted_coding.xlsx')

data[data == "N/A"] <- NA
data$JA[is.na(data$JA)] <- 0
data$JA <- as.numeric(data$JA)
```

```{r}
# 组间
group_compare <- function(group_name_1, group_name_2) {
  print(wilcox.test(group_name_1$JA, group_name_2$JA, paired = FALSE))
  print(wilcox.test(group_name_1$SA, group_name_2$SA, paired = FALSE))
  print(wilcox.test(group_name_1$ABA, group_name_2$ABA, paired = FALSE))
}

# 组内
within_comparison <- function(group_name_1, group_name_2) {
  print(wilcox.test(group_name_1$JA, group_name_2$JA, paired = TRUE))
  print(wilcox.test(group_name_1$SA, group_name_2$SA, paired = TRUE))
  print(wilcox.test(group_name_1$ABA, group_name_2$ABA, paired = TRUE))
}
```


Between-group comparison：
Test: similar level of metabolites on day 1
```{r}
# data filter
day_1_control <- data %>%
  filter(str_sub(exp_group,1,3) == "Con" & time_point == 1)

day_1_H1 <- data %>%
  filter(str_sub(exp_group,1,4) == "H1st" & time_point == 1)

day_1_F1 <- data %>%
  filter(str_sub(exp_group,1,4) == "F1st" & time_point == 1)

#Mann-Whitney U检验
group_compare(day_1_control,day_1_H1)
group_compare(day_1_control,day_1_F1)
group_compare(day_1_F1,day_1_H1)


```

Day2:
```{r}
# data filter
day_2_control <- data %>%
  filter(str_sub(exp_group,1,3) == "Con" & time_point == 2)

day_2_H1 <- data %>%
  filter(str_sub(exp_group,1,4) == "H1st" & time_point == 2)

day_2_F1 <- data %>%
  filter(str_sub(exp_group,1,4) == "F1st" & time_point == 2)

#Mann-Whitney U检验
group_compare(day_2_control,day_2_H1)
group_compare(day_2_control,day_2_F1)
group_compare(day_2_F1,day_2_H1)
```

Day3:
```{r}
# data filter
day_3_control <- data %>%
  filter(str_sub(exp_group,1,3) == "Con" & time_point == 3)

day_3_H1 <- data %>%
  filter(str_sub(exp_group,1,4) == "H1st" & time_point == 3)

day_3_F1 <- data %>%
  filter(str_sub(exp_group,1,4) == "F1st" & time_point == 3)

#Mann-Whitney U检验
group_compare(day_3_control,day_3_H1)
group_compare(day_3_control,day_3_F1)
group_compare(day_3_F1,day_3_H1)
```

Within-group comparison
```{r}
within_comparison(day_1_control,day_2_control)
within_comparison(day_2_control,day_3_control)

within_comparison(day_1_H1,day_2_H1)
within_comparison(day_2_H1,day_3_H1)

within_comparison(day_1_F1,day_2_F1)
within_comparison(day_2_F1,day_3_F1)
```

# DADY_untargeted_coding_setup
```{r}
sink("output_log.txt") # 将R的输出重定向到一个文件
```

```{r}
library(dplyr)
full_data <- read_excel("DADY_untargeted_coding_setup.xlsx")
print(full_data[2, ])
exp_data = full_data[9:388, ]
exp_data[exp_data == "N/A"] <- NA
exp_data[is.na(exp_data)] <- "0"
exp_data[3:29] <- lapply(exp_data[3:29], as.numeric)
```
```{r}
# 组间
group_compare_fulldata <- function(group_name_1, group_name_2) {
  wilcox_result = wilcox.test(group_name_1, group_name_2, paired = FALSE)
  capture.output(print(wilcox_result), file = "output_log.txt", append = TRUE)
}

# 组内
within_comparison_fulldata <- function(group_name_1, group_name_2) {
  wilcox_result = wilcox.test(group_name_1, group_name_2, paired = TRUE)
  capture.output(print(wilcox_result), file = "output_log.txt", append = TRUE)
}

for (i in 1:nrow(exp_data)) {
  row_data <- exp_data[i, ]
  cat("Between-group comparison:\nTest: similar level of metabolites on day 1\n", file = "output_log.txt", append = TRUE)
  day_1_control <- as.numeric(row_data[3:5])
  day_1_H1 <- as.numeric(row_data[6:8])
  day_1_F1 <- as.numeric(row_data[9:11])
  
  group_compare_fulldata(day_1_control,day_1_H1)
  group_compare_fulldata(day_1_control,day_1_F1)
  group_compare_fulldata(day_1_F1,day_1_H1)
  
  cat("Between-group comparison:\nTest: similar level of metabolites on day 2\n", file = "output_log.txt", append = TRUE)
  day_2_control <- as.numeric(row_data[12:14])
  day_2_H1 <- as.numeric(row_data[15:17])
  day_2_F1 <- as.numeric(row_data[18:20])
  
  group_compare_fulldata(day_2_control,day_2_H1)
  group_compare_fulldata(day_2_control,day_2_F1)
  group_compare_fulldata(day_2_F1,day_2_H1)
  
  cat("Between-group comparison:\nTest: similar level of metabolites on day 3\n", file = "output_log.txt", append = TRUE)
  day_3_control <- as.numeric(row_data[21:23])
  day_3_H1 <- as.numeric(row_data[24:26])
  day_3_F1 <- as.numeric(row_data[27:29])
  
  group_compare_fulldata(day_3_control,day_3_H1)
  group_compare_fulldata(day_3_control,day_3_F1)
  group_compare_fulldata(day_3_F1,day_3_H1)
  
  cat("Within-group comparison\n", file = "output_log.txt", append = TRUE)
  within_comparison_fulldata(day_1_control,day_2_control)
  within_comparison_fulldata(day_2_control,day_3_control)
  
  within_comparison_fulldata(day_1_H1,day_2_H1)
  within_comparison_fulldata(day_2_H1,day_3_H1)
  
  within_comparison_fulldata(day_1_F1,day_2_F1)
  within_comparison_fulldata(day_2_F1,day_3_F1)
}


```

```{r}
sink() # 停止重定向输出
```




